server:
  port: 8080

spring:
  application:
    name: bank-cards-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards_db
    username: postgres
    password: 711204711204
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  liquibase:
    change-log: classpath:db/migration/changelog-1.0.yaml

  logging:
    level:
      root: INFO
      org.springframework: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: my-super-secret-key-change-in-prod
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

encryption:
  aes-key: "MySecretKey12345"
